== Subwavelength physics

=== Introduction

This project serves as code base for the research mainly based at ETH Zürich in the group of Prof. Dr H. Ammari and more recently at MIT.

Maintainers of the repository are:

.Maintainers
* Silvio Barandun (barandun at mit.edu)
* Alexander Uhlmann (alexander.uhlmann at sam.math.ethz.ch)

You can cite this repo as
----
@software{barandun.uhlmannSubwavelength,
  title = {Subwavelength Physics},
  author = {Barandun, Silvio and Uhlmann, Alexander},
  url = {https://github.com/silvioba/subwavelength-physics},
  version = {v3.0}
}
----

=== Optional dependencies

==== FMM
@auhlmann developed a great idea on how to make the 3D code faster using the fast multipole method (FMM). This was introduced in v2 and is still available in v3. FMM needs a good library to run, which python does not provide out of the box. Here below you find a step-by-step guide on how to get this to work. The indications are for linux/ubuntu shell, but it should not be too different on other devices.

. Create a python3.11 virtual environment
+
[source,shell]
----
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.11
sudo apt install python3.11-venv

mkdir venv_fmm
python3.11 -m venv venv_fmm
source venv/bin/activate
----

. Navigate to the `subwavelength-physics` dir and run `pip install -r requirements.txt`

. We use the Flat Iron Institute's FMM library (https://github.com/flatironinstitute/FMM3D) which has a python wrapper. You can download here https://github.com/flatironinstitute/FMM3D/releases/tag/v1.0.4 the v1.0.4 of the library and unzip it somewhere in your files.

. If you do not have `gfortran` installed (i.e. if `which gfortran` does not return anything to your terminal) you need to install this via `sudo apt install gfortran`. We tested this with verion `GNU Fortran (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0` which you can find out with `gfortran --version`

. Now you will need to install the FMM library. Open a terminal inside of the unziped dir of step 3 and run `make install` (for other OS see the guide here: https://fmm3d.readthedocs.io/en/latest/install.html). If everything work you should be able to run `make test` successfully.

. Now you need the python wrapper. To do this run `make python` from the same dir. You probably need also to run `sudo apt install python3.11-dev build-essential gfortran` before this step. Now you should be able to run `python python/test/test_hfmm.py`

==== Epstein zeta (v3.0)
`Subwavelength3D/epstein.py` provides a faster monopole-only quasiperiodic capacitance matrix via the Epstein zeta function. It requires the `epsteinlib` package:

[source,shell]
----
pip install epsteinlib
----

If `epsteinlib` is not installed, importing `Subwavelength3D.epstein` raises an `ImportError` with installation instructions. All other 3D functionality is unaffected.

=== Project Structure
----
.
├── Demos                                      # Demo Notebooks
│   ├── 1D.ipynb
│   └── 3D.ipynb
├── Subwavelength1D                            # 1D code
│   ├── paper_plots                            
│   ├── classic.py
│   ├── disordered.py
│   ├── exceptional_point.py
│   ├── M_matrix.py
│   ├── metaatom.py
│   ├── nonreciprocal.py
│   ├── quasiperiodic.py
│   ├── simulation.py
│   ├── swp.py
│   └── time_modulated.py
├── Subwavelength3D                             # 3D code
│   ├── classic_finite.py                      
│   ├── classic_periodic.py                    
│   ├── nonreciprocal.py                       
│   ├── epstein.py                             
│   ├── fmm.py                                 
│   ├── swp.py
│   └── theory.adoc
├── tests
│   ├── test_3D_finite.py
│   ├── test_3D_periodic.py
│   ├── test_3D_nonreciprocal.py               
│   ├── test_3D_nonreciprocal_periodic.py      
│   ├── test_3D_periodic_epstein.py            
│   ├── test_classic.py
│   ├── test_nonreciprocal.py
│   └── test_utils.py
├── Utils                                       # General function that may be usefull
│   ├── plots_exploration.py
│   ├── settings.py
│   ├── tools.py
│   ├── utils_general.py
│   └── utils_propagation.py
├── .gitignore
├── bib.bib                                     # Refs to papers
├── README.adoc
└── requirements.txt
----

=== Scientific backgrounds
This code builds on various publications. You can find them in the file `bib.bib`.

=== Coding guidelines for contributions
1. Use google docstrings
2. We highly encourage to write tests for all parts of the code
